CONTAINER tCDClothTag
{
	NAME tCDClothTag;
	DEFAULT 1;
	GROUP
	{
		BUTTON CL_PURCHASE {}
	}
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		DEFAULT	1;
		
		GROUP
		{
			COLUMNS 1;
			
			REAL CL_DAMPING { UNIT PERCENT; MIN 1; MAX 100; }
			REAL CL_STIFFNESS { UNIT PERCENT; MIN 0; MAX 100; }
			REAL CL_TIME_STEP { UNIT REAL; MIN 0.0; MAX 100.0; STEP 0.1; }
			LONG CL_ITERATIONS { MIN 1; MAX 100; }

			GROUP
			{
				COLUMNS 2;
				
				BOOL CL_USE_GRAVITY { }
				REAL CL_GRAVITY { UNIT REAL; STEP 0.1;}
			}
			
			BOOL CL_DEBUG_DRAW { }
		}
	}
	GROUP CL_WIND_GROUP
	{
		GROUP
		{
			COLUMNS 1;
				
			VECTOR CL_WIND_DIRECTION { UNIT REAL; MIN 0.0; MAX 1; STEP 0.1;  }
			REAL CL_WIND_STRENGTH { UNIT REAL; MIN 0.0; MAX 100; STEP 0.1; }
		}
		SEPARATOR { LINE; }
		GROUP
		{
			BOOL CL_USE_TURBULENCE { }
			REAL CL_TURBULENCE_FREQUENCY { UNIT REAL; MIN 0.0; MAX 100; STEP 0.1; }
			REAL CL_TURBULENCE_AMPLITUDE { UNIT REAL; MIN 0.0; MAX 100; STEP 0.1; }
			REAL CL_TURBULENCE_SPEED { UNIT REAL; MIN 0.0; MAX 100; STEP 0.1; }
		}
	}
}