CONTAINER tCDRopeTag
{
	NAME tCDRopeTag;
	DEFAULT 1;
	GROUP
	{
		BUTTON RP_PURCHASE {}
	}
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		DEFAULT	1;
		
		GROUP
		{
			COLUMNS 1;
			
			REAL RP_DAMPING { UNIT PERCENT; MIN 1; MAX 100; }
			REAL RP_STIFFNESS { UNIT PERCENT; MIN 0; MAX 100; }
			REAL RP_TIME_STEP { UNIT REAL; MIN 1.0; MAX 10.0; STEP 0.1; }
			LONG RP_ITERATIONS { MIN 1; MAX 1000; }
			BOOL RP_KEEP_SHAPE { }
			
			GROUP
			{
				COLUMNS 2;
				
				BOOL RP_USE_GRAVITY { }
				REAL RP_GRAVITY { UNIT REAL; STEP 0.1;}
			}
		}
	}
	GROUP RP_WIND_GROUP
	{
		GROUP
		{
			COLUMNS 1;
				
			VECTOR RP_WIND_DIRECTION { UNIT REAL; MIN 0.0; MAX 1; STEP 0.1;  }
			REAL RP_WIND_STRENGTH { UNIT REAL; MIN 0.0; MAX 100; STEP 0.1; }
		}
		SEPARATOR { LINE; }
		GROUP
		{
			BOOL RP_USE_TURBULENCE { }
			REAL RP_TURBULENCE_FREQUENCY { UNIT REAL; MIN 0.0; MAX 100; STEP 0.1; }
			REAL RP_TURBULENCE_AMPLITUDE { UNIT REAL; MIN 0.0; MAX 100; STEP 0.1; }
			REAL RP_TURBULENCE_SPEED { UNIT REAL; MIN 0.0; MAX 100; STEP 0.1; }
		}
	}
}