enum
{
	// string table definitions
	IDS_CDLIMBIK			= 10000,
	IDS_CDFOOTIK			= 10001,
	IDS_CDROTATOR			= 10002,
	IDS_CDDUALTARGET		= 10003,
	IDS_CDFINGER			= 10004,
	IDS_CDTHUMB				= 10005,
	IDS_CDSPLINEIK			= 10006,
	
	IDS_ABOUTCD				= 10007,
	IDS_ROOTNULL			= 10008,
	IDS_TIPEFFECTOR			= 10009,
	IDS_TIPNULL				= 10010,
	IDS_ZEROGROT			= 10011,
	IDS_SERIALMAKER			= 10012,

	IDC_SERIALNUMBER		= 10013,
	IDC_ABOUT_IMAGE			= 10014,
	IDC_ABOUT_PLUGININFO	= 10015,
	IDC_WEBSITE_INFO		= 10016,
	
	IDS_CPYHPOSE			= 10017,
	IDS_POSE_INDEX			= 10018,
	
	IDS_TIPGOAL				= 10019,
	IDS_ADDHAND				= 10020,
	IDS_CDIKSETUP			= 10021,
	
	DLG_SETUP				= 10022,
	IDC_EXPRESSION_TYPE		= 10023,
	IDC_SPLINE_TARGETS		= 10024,
	IDC_SOLVER_AXIS			= 10025,
	IDC_SOLVER_LINE			= 10026,
	IDC_CDIKTOOLSNUMBER		= 10027,

	IDS_CDSPINAL			= 10028,
	IDC_SPINAL_AXIS			= 10029,
	
	IDS_CDHAND				= 10030,
	IDS_CDQUADLEG			= 10031,
	
	IDS_CDMCHLIMB			= 10032,
	IDS_ZEROLROT			= 10033,
	
	IDS_CDSMOOTHROT			= 10034,
	IDS_CDIKHNDL			= 10035,
	IDS_CDADDHNDL			= 10036,
	IDS_CDLNKGIK			= 10037,
	IDS_CDPSTNIK			= 10038,
	
	IDS_SAVEHPOSE			= 10039,
	IDS_LOADHPOSE			= 10040,
	
	DLG_CDIK_ABOUT			= 20000,
	DLG_CDIK_REGISTER,
	IDC_CDIK_ABOUT_IMAGE,
	IDC_CDIK_ABOUT_PLUGININFO,
	IDC_CDIK_SERIALNUMBER,
	
	IDC_CDIK_UPDATE,
	IDC_CDIK_REGISTER,
	IDC_CDIK_CANCEL,
	IDC_CDIK_PURCHASE,
	
	IDC_CDIK_EULA,
	IDC_CDIK_AGREE,
	IDC_CDIK_DISAGREE,

	DLG_CDIK_OPTIONS,
	IDC_CDIK_OPTIONS_IMAGE,

	IDS_WEB_SITE,
	
	C_SYMBOL,
	
	// CDIK HANDLE TOOL
	IDS_SOLVER_TYPE			=30000,
		IDS_IKRP,
		IDS_IKSC,
		IDS_IKHD,
	IDS_POLE_AXIS,
		IDS_POLE_X,
		IDS_POLE_Y,
		IDS_POLE_NX,
		IDS_POLE_NY,
	IDS_TOOL_RADIUS,

	
	// CD IK SETUP DIALOG
	D_TITLE 			= 50000,

	D_EXPR_TYPE,			
		D_LIMB,
		D_QUAD,
		D_MECH,
		D_FOOT,
		D_FINGER,
		D_THUMB,
		D_ROTATOR,
		D_SPLINE,
		D_SPINE,
		D_LINKAGE,
		D_PISTON,
  
	D_SOLVER_AXIS,
	D_SPINAL_AXIS,
  
		D_X,
		D_Y,
		D_Z,
		D_NX,
		D_NY,
		D_NZ,
  
	D_LN_TARGET,
		D_ROOT,
		D_TIP,
  	
	D_SPL_TARGET,
		D_SPL_TARG_A,
		D_SPL_TARG_B,
		D_SPL_TARG_C,
		D_SPL_TARG_D,
		
	D_NUM_BONES,
	
	D_SETUP_CHAIN,

	// CD Hand strings
	H_FINGER = 60000,
	
	H_GRIP,
	H_TWIST,
	H_SPREAD,
	H_BEND,
	H_CURL,
	H_DAMPING,
	H_BND_N_CRL,
	
	H_POSE,
	H_POSE_SET,
	H_POSE_EDIT,
	H_POSE_MIX,
	H_POSE_RESTORE,
	
	// CD Spline IK strings
	S_TARGET,
	S_BANKING,
	
	// Null object Strings
	N_ROOT_NULL,
	N_TIP_EFFECTOR,
	N_TIP_NULL,
	N_TIP_GOAL,
	N_SOLVER,
	N_ROTATOR,
	N_SPLINE,
	N_MID_GOAL,
	N_BASE_C,
	N_TIP_C,
	N_LIMB_IK,
	N_QUADLEG_IK,
	N_MECH_IK,
	N_FOOT_IK,
	N_SPLINE_IK,
	N_SPINAL,
	N_LINK_IK,
	N_PISTON_IK,

	MD_PLEASE_REGISTER,
	MD_INVALID_NUMBER,
	MD_THANKYOU,
	MD_TOO_MANY_OBJECTS,
	MD_CDHAND_TAGS_NOT_EQUAL,
	MD_SELECT_CDHAND_TAG,
	MD_FILE_DOES_NOT_MATCH_CDHTAG,
	MD_OVERWRITE_FILE
};
