enum
{
	// string table definitions
	IDS_CDTSCOMMAND			= 10000,
	IDS_TRANSELTAG			= 10001,
	IDS_CDZTRANS			= 10002,
	IDS_CDADDZT				= 10003,
	IDS_CDADDTSL			= 10004,
	IDS_ZEROGROT			= 10005,
	IDS_CDCOORDS			= 10006,
	IDS_CDTRANSFER			= 10007,
	IDS_ZEROLROT			= 10008,
	IDS_CDSELSAME			= 10009,
	IDS_CDMIRTRANS			= 10010,
	IDS_CDREPLTRANS			= 10011,
	IDS_ABOUTCDT			= 10012,
	IDS_CDSWPTRANS			= 10013,
	IDS_CDUNLINK			= 10014,
	IDS_CDLINK				= 10015,
	IDS_CDTRANSGOAL			= 10016,
	IDS_CDFTRANS			= 10017,
	IDS_CDSETZHOME			= 10018,
	IDS_CDAIMTRANS			= 10019,
	//IDS_CDAKCOMMAND			= 10020,
	IDS_CDTRANSANIM			= 10021,
	IDS_CDUDTRANS			= 10022,
	IDS_CDTRANSAXIS			= 10023,
	IDS_TRANSACTTAG			= 10024,
	
	IDS_HLP_CNTRL_CLICK		= 10100,
	
	DLG_CDTR_ABOUT			= 20000,
	DLG_CDTR_REGISTER,
	IDC_CDTR_ABOUT_IMAGE,
	IDC_CDTR_ABOUT_PLUGININFO,
	IDC_CDTR_SERIALNUMBER,
	IDC_WEBSITE_INFO,
	
	IDC_CDTR_UPDATE,
	IDC_CDTR_REGISTER,
	IDC_CDTR_CANCEL,
	IDC_CDTR_PURCHASE,
	
	DLG_CDTR_OPTIONS,
	IDC_CDTR_OPTIONS_IMAGE,

	IDS_WEB_SITE,
	
	C_SYMBOL,

	CDTR_TITLE 			= 30000,
	CDTR_TYPE,
	
	CDTR_TRANSFER,
	CDTR_POS,
	CDTR_POS_X,
	CDTR_POS_Y,
	CDTR_POS_Z,
	CDTR_SCA,
	CDTR_ROT,
	
	CDTR_MIRROR,
	CDTR_MIR_GLOBAL,
	CDTR_MIR_LOCAL,
	CDTR_AXIS,
	CDTR_MIR_X,
	CDTR_MIR_Y,
	CDTR_MIR_Z,
	
	CDTR_REPLACE,
	CDTR_SWAP,
	CDTR_FREEZE,
	CDTR_FRZ_PRIM,
	CDTR_FRZ_CHILD,
	
	CDTR_GROUP,
	CDTR_TO_GROUP,
	CDTR_TO_LAST,
	
	CDTR_AIM,
	IDC_CDTR_EULA,
	IDC_CDTR_AGREE,
	IDC_CDTR_DISAGREE,
	
	CDTR_AUTO_KEY,
	CDTR_KEEP_SELECTION,
	CDTR_KEYS,
	
	HIERARCHAL_ALIGN,
	
	CDTR_SINGLE,
	CDTR_MULTIPLE,
	
	CDTR_NORMAL_AXIS,
	CDTR_LOCK_M_AXIS,
	
	CDTR_A_GROUP,
	CDTR_MODE,
	
	CDTR_ANIM_HRCHY,
	CDTR_ANIM_POS,
	CDTR_ANIM_SCA,
	CDTR_ANIM_ROT,
	CDTR_ANIM_AM,
	CDTR_ANIM_UD,
	
	CDTR_COMPONENTS_ONLY,
	CDTR_AXES,
	CDTR_YZX,
	CDTR_ZXY,
	CDTR_YXZ,
	CDTR_XYZ,
	
	CDTR_NAME,
	CDTR_NONE,
	
	CDCM_TITLE 			= 50000,
	CDCM_UNITS,
	CDCM_UNIT_SCALE,
	CDCM_COORDS,
	CDCM_KM,
	CDCM_M,
	CDCM_CM,
	CDCM_MM,
	CDCM_MI,
	CDCM_YD,
	CDCM_IN,
	CDCM_FT,
	
	CDCM_P_GROUP,
	CDCM_X_POS,
	CDCM_Y_POS,
	CDCM_Z_POS,
	
	CDCM_S_GROUP,
	CDCM_S_GRP_NAME,
	CDCM_X_SCA,
	CDCM_Y_SCA,
	CDCM_Z_SCA,
	
	CDCM_R_GROUP,
	CDCM_H_ROT,
	CDCM_P_ROT,
	CDCM_B_ROT,
	
	CDCM_LOCAL,
	CDCM_GLOBAL,
	CDCM_OBJECT_PLUS,
	
	CDCM_SCALE,
	CDCM_SIZE,
	CDCM_SIZE_PLUS,
	
	CDCM_DEGREE,
	CDCM_RADIAN,
	
	CDCM_APPLY,
	
	CDCM_SCALE_THREE,
	CDCM_SIZE_THREE,
	
	MD_TOO_MANY_OBJECTS,
	MD_AT_LEAST_TWO,
	MD_SELECT_SINGLE,
	MD_PLEASE_REGISTER,
	MD_INVALID_NUMBER,
	MD_THANKYOU,
	MD_ALL_OPTIONS_OFF,
	MD_HIERARCHY_NOT_SAME,
	MD_USER_DATA_NOT_SAME
	
};
