// C4D-DialogResource

DIALOG DLG_CDJS_ABOUT
{
	NAME CDJS_TITLE;
	GROUP
	{
		COLUMNS 1;
   		BORDERSIZE 8,8,8,8;
		BORDERSTYLE BORDER_GROUP_IN;
		
		USERAREA IDC_CDJS_ABOUT_IMAGE { CENTER_H; SIZE -320,-60; }
		
		STATICTEXT IDC_CDJS_ABOUT_PLUGININFO { NAME CDJS_PLUGININFO; CENTER_H; }
		STATICTEXT IDC_WEBSITE_INFO { NAME WEBINFO; CENTER_H; }
		BUTTON IDC_CDJS_UPDATE { NAME CDJS_UPDATE; CENTER_H; SIZE -240,-18;  }
		GROUP
		{
			COLUMNS 1;
			NAME CDJS_SERIAL;
			BORDERSIZE 12,6,12,6;
			BORDERSTYLE BORDER_GROUP_IN;
			SCALE_H;

			EDITTEXT IDC_CDJS_SERIALNUMBER { SCALE_H; }
		}
	}

	DLGGROUP { OK; }
}
