// C4D-DialogResource

DIALOG DLG_CDJS_REGISTER
{
	NAME CDJS_TITLE;
	GROUP
	{
		COLUMNS 1;
   		BORDERSIZE 8,8,8,8;
		BORDERSTYLE BORDER_GROUP_IN;
		
		USERAREA IDC_CDJS_ABOUT_IMAGE { CENTER_H; SIZE -320,-60; }
		
		STATICTEXT IDC_CDJS_ABOUT_PLUGININFO { NAME CDJS_PLUGININFO; CENTER_H; }
		STATICTEXT IDC_WEBSITE_INFO { NAME WEBINFO; CENTER_H; }
		GROUP
		{
			COLUMNS 1;
			NAME CDJS_SERIAL;
			BORDERSIZE 12,6,12,6;
			BORDERSTYLE BORDER_GROUP_IN;
			SCALE_H;

			EDITTEXT IDC_CDJS_SERIALNUMBER { SCALE_H; }
		}
	}

	GROUP
	{
		COLUMNS 3;
		CENTER_H;
   		BORDERSIZE 8,8,8,8;
		BORDERSTYLE BORDER_NONE;
		
		BUTTON IDC_CDJS_CANCEL { NAME CDJS_CANCEL; CENTER_H; SIZE -40,-18; }
		BUTTON IDC_CDJS_REGISTER { NAME CDJS_REGISTER; CENTER_H; SIZE -40,-18; }
		BUTTON IDC_CDJS_PURCHASE { NAME CDJS_PURCHASE; CENTER_H; SIZE -40,-18; }
	}
}
