// C4D-DialogResource

DIALOG DLG_CDC_ABOUT
{
	NAME CDC_TITLE;
	GROUP
	{
		COLUMNS 1;
   		BORDERSIZE 8,8,8,8;
		BORDERSTYLE BORDER_GROUP_IN;
		
		USERAREA IDC_CDC_ABOUT_IMAGE { CENTER_H; SIZE -320,-60; }
		
		STATICTEXT IDC_CDC_ABOUT_PLUGININFO { NAME CDC_PLUGININFO; CENTER_H; }
		STATICTEXT IDC_WEBSITE_INFO { NAME WEBINFO; CENTER_H; }
		BUTTON IDC_CDC_UPDATE { NAME CDC_UPDATE; CENTER_H; SIZE -240,-18;  }
		GROUP
		{
			COLUMNS 1;
			NAME CDC_SERIAL;
			BORDERSIZE 12,6,12,6;
			BORDERSTYLE BORDER_GROUP_IN;
			SCALE_H;

			EDITTEXT IDC_CDC_SERIALNUMBER { SCALE_H; }
		}
	}

	DLGGROUP { OK; }
}
