// C4D-DialogResource

DIALOG DLG_CDFBX_REGISTER
{
	NAME CDFBX_TITLE;
	GROUP
	{
		COLUMNS 1;
   		BORDERSIZE 8,8,8,8;
		BORDERSTYLE BORDER_GROUP_IN;
		
		USERAREA IDC_CDFBX_ABOUT_IMAGE { CENTER_H; SIZE -320,-60; }
		STATICTEXT IDC_CDFBX_SDK_INFO { NAME CDFBX_SDK_INFO; CENTER_H; }
		
		STATICTEXT IDC_CDFBX_ABOUT_PLUGININFO { NAME CDFBX_PLUGININFO; CENTER_H; }
		STATICTEXT IDC_WEBSITE_INFO { NAME WEBINFO; CENTER_H; }
		GROUP
		{
			COLUMNS 1;
			NAME CDFBX_SERIAL;
			BORDERSIZE 12,6,12,6;
			BORDERSTYLE BORDER_GROUP_IN;
			SCALE_H;

			EDITTEXT IDC_CDFBX_SERIALNUMBER { SCALE_H; }
		}
	}

	GROUP
	{
		COLUMNS 3;
		CENTER_H;
   		BORDERSIZE 8,8,8,8;
		BORDERSTYLE BORDER_NONE;
		
		BUTTON IDC_CDFBX_CANCEL { NAME CDFBX_CANCEL; CENTER_H; SIZE -40,-18; }
		BUTTON IDC_CDFBX_REGISTER { NAME CDFBX_REGISTER; CENTER_H; SIZE -40,-18; }
		BUTTON IDC_CDFBX_PURCHASE { NAME CDFBX_PURCHASE; CENTER_H; SIZE -40,-18; }
	}
}
