CONTAINER tCDZeroTrans
{
	NAME tCDZeroTrans;
	DEFAULT 1;
	GROUP
	{
		BUTTON ZT_PURCHASE {}
	}
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		DEFAULT	1;
				
		GROUP
		{
			COLUMNS 2;
			
			BUTTON ZT_ZERO_COORDS {}
			BUTTON ZT_RETURN_TO_ZERO {}
		}
		SEPARATOR {}
		GROUP
		{
			LAYOUTGROUP; COLUMNS 3;
			GROUP { VECTOR ZT_TRANS_POS { UNIT REAL; ANIM ON; CUSTOMGUI SUBDESCRIPTION; } }
			GROUP { VECTOR ZT_TRANS_SCA { STEP 0.01; ANIM ON; CUSTOMGUI SUBDESCRIPTION; } }
			GROUP { VECTOR ZT_TRANS_ROT { UNIT DEGREE; ANIM ON; CUSTOMGUI SUBDESCRIPTION; } }
		}
		SEPARATOR {}
		GROUP
		{
			COLUMNS 1;
			BOOL ZT_LOCK_ZERO_TRANS {}
			
		}
	}
}