// C4D-DialogResource

DIALOG DLG_CDIK_ABOUT
{
	NAME TITLE;
	GROUP
	{
		COLUMNS 1;
   		BORDERSIZE 8,8,8,8;
		BORDERSTYLE BORDER_GROUP_IN;
		
		USERAREA IDC_CDIK_ABOUT_IMAGE { CENTER_H; SIZE -320,-60; }
		
		STATICTEXT IDC_CDIK_ABOUT_PLUGININFO { NAME CDIK_PLUGININFO; CENTER_H; }
		STATICTEXT IDC_WEBSITE_INFO { NAME WEBINFO; CENTER_H; }
		BUTTON IDC_CDIK_UPDATE { NAME CDIK_UPDATE; CENTER_H; SIZE -240,-18;  }
		
		GROUP
		{
			COLUMNS 1;
			NAME CDIKTOOLS_SERIAL;
			BORDERSIZE 12,6,12,6;
			BORDERSTYLE BORDER_GROUP_IN;
			SCALE_H;

			EDITTEXT IDC_CDIK_SERIALNUMBER { SCALE_H; }
		}
	}

	DLGGROUP { OK; }
}
