CONTAINER oCDJoint
{
	NAME oCDJoint;
	DEFAULT 1;
	GROUP
	{
		BUTTON JNT_PURCHASE {}
	}
	INCLUDE Obase;

	GROUP Obaselist
	{
		PRIORITY JNT_PRIORITY { ANIM OFF; }
	}
	
	GROUP ID_OBJECTPROPERTIES
	{
		GROUP
		{
			COLUMNS 2;
			BOOL JNT_CONNECTED { }
			BOOL JNT_SHOW_LOCAL_AXIS { }
		}
		REAL JNT_JOINT_RADIUS { UNIT METER; MIN 0.01; STEP 0.1; }
		SEPARATOR {}
		BUTTON JNT_ORIENT_JOINT {}

	}
	GROUP JNT_ID_TRANSFORM
	{
		DEFAULT 1;
		
		GROUP
		{
			COLUMNS 2;
			
			BUTTON JNT_ZERO_COORDS {}
			BUTTON JNT_RETURN_TO_ZERO {}
		}
		SEPARATOR {}
		GROUP
		{
			LAYOUTGROUP; COLUMNS 3;
			GROUP { VECTOR JNT_TRANS_POS { UNIT REAL;  CUSTOMGUI SUBDESCRIPTION; } }
			GROUP { VECTOR JNT_TRANS_SCA { STEP 0.01;   CUSTOMGUI SUBDESCRIPTION; } }
			GROUP { VECTOR JNT_TRANS_ROT { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; } }
		}
		SEPARATOR {}
		GROUP
		{
			COLUMNS 1;
			BOOL JNT_LOCK_ZERO_TRANS {}
			
		}
	}
	GROUP JNT_ID_ENVELOPE
	{
		DEFAULT 1;
		
		GROUP
		{
			COLUMNS 2;
			BOOL JNT_SHOW_ENVELOPE { }
			BOOL JNT_SHOW_PROXY { }
		}
		SEPARATOR {}
		GROUP
		{
			COLUMNS 1;
			VECTOR JNT_ROOT_OFFSET { UNIT METER; STEP 0.1; }
			VECTOR JNT_TIP_OFFSET { UNIT METER; STEP 0.1; }
		}
		SEPARATOR {}
		GROUP
		{
			COLUMNS 2;
			REAL JNT_SKEW_RX { UNIT METER; STEP 0.1; }
			REAL JNT_SKEW_RY { UNIT METER; STEP 0.1; }
			REAL JNT_SKEW_TX { UNIT METER; STEP 0.1; }
			REAL JNT_SKEW_TY { UNIT METER; STEP 0.1; }
		}
	}
}
