CONTAINER tCDCluster
{
	NAME tCDCluster;
	DEFAULT 1;
	GROUP
	{
		BUTTON CLST_PURCHASE {}
	}
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		DEFAULT	1;
		
		GROUP 
		{ 
			COLUMNS 1;
			LINK  CLST_DEST_LINK { ANIM ON; ACCEPT { Obase; } }
		}
		SEPARATOR {LINE;}	
		GROUP
		{
			COLUMNS 2;
			
			BUTTON CLST_BIND_POINTS {}
			BUTTON CLST_UNBIND_POINTS {}
		}
		GROUP 
		{ 
			COLUMNS 2;
			BOOL  CLST_MIX_PREVIOUS {}
			BOOL  CLST_LOCAL_TRANS {}
		}
	}
	GROUP CLST_ID_CLUSTERBLEND
	{
		GROUP 
		{ 
			COLUMNS 1;
			BOOL CLST_BLEND_ROTATION {}
			REAL CLST_ROT_MIX { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER;}
		}
		SEPARATOR {LINE;}	
		GROUP 
		{ 
			COLUMNS 1;
			BOOL CLST_ATTACH_CHILD {}
		}
		GROUP 
		{ 
			COLUMNS 2;
			BOOL CLST_ATTACH_EXTERNAL {}
			LINK CLST_ATTACH_LINK { ANIM ON; ACCEPT { Obase; } }
		}
		SEPARATOR {LINE;}	
		GROUP 
		{ 
			COLUMNS 2;
			BOOL CLST_SHOW_GUIDE {}
			REAL CLST_GUIDE_SIZE { UNIT REAL; MIN 0.0; }
		}
		GROUP 
		{ 
			COLUMNS 1;
			COLOR CLST_LINE_COLOR {}
			VECTOR CLST_JOINT_OFFSET	{ UNIT REAL; STEP 0.1; }
			BOOL CLST_ENABLE_PIVOT {}
			VECTOR CLST_PIVOT_OFFSET	{ UNIT REAL; STEP 0.1; }
			VECTOR CLST_CHILD_OFFSET	{ UNIT REAL; STEP 0.1; }
			BOOL CLST_RESTRICT_TO_Z {}
			REAL CLST_POS_MIX { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER;}
		}
		SEPARATOR {LINE;}	
		GROUP 
		{ 
			COLUMNS 1;
			VECTOR CLST_STRENGTH	{  UNIT PERCENT; MIN 0.0; MAX 100.0; }
		}
	}
}