// C4D-DialogResource

DIALOG DLG_CDCL_ABOUT
{
	NAME CDCL_TITLE;
	GROUP
	{
		COLUMNS 1;
   		BORDERSIZE 8,8,8,8;
		BORDERSTYLE BORDER_GROUP_IN;
		
		USERAREA IDC_CDCL_ABOUT_IMAGE { CENTER_H; SIZE -320,-60; }
		
		STATICTEXT IDC_CDCL_ABOUT_PLUGININFO { NAME CDCL_PLUGININFO; CENTER_H; }
		STATICTEXT IDC_WEBSITE_INFO { NAME WEBINFO; CENTER_H; }
		BUTTON IDC_CDCL_UPDATE { NAME CDCL_UPDATE; CENTER_H; SIZE -240,-18;  }
		GROUP
		{
			COLUMNS 1;
			NAME CDCL_SERIAL;
			BORDERSIZE 12,6,12,6;
			BORDERSTYLE BORDER_GROUP_IN;
			SCALE_H;

			EDITTEXT IDC_CDCL_SERIALNUMBER { SCALE_H; }
		}
	}

	DLGGROUP { OK; }
}
