// C4D-DialogResource

DIALOG DLG_CDCL_REGISTER
{
	NAME CDCL_TITLE;
	GROUP
	{
		COLUMNS 1;
   		BORDERSIZE 8,8,8,8;
		BORDERSTYLE BORDER_GROUP_IN;
		
		USERAREA IDC_CDCL_ABOUT_IMAGE { CENTER_H; SIZE -320,-60; }
		
		STATICTEXT IDC_CDCL_ABOUT_PLUGININFO { NAME CDCL_PLUGININFO; CENTER_H; }
		STATICTEXT IDC_WEBSITE_INFO { NAME WEBINFO; CENTER_H; }
		GROUP
		{
			COLUMNS 1;
			NAME CDCL_SERIAL;
			BORDERSIZE 12,6,12,6;
			BORDERSTYLE BORDER_GROUP_IN;
			SCALE_H;

			EDITTEXT IDC_CDCL_SERIALNUMBER { SCALE_H; }
		}
	}

	GROUP
	{
		COLUMNS 3;
		CENTER_H;
   		BORDERSIZE 8,8,8,8;
		BORDERSTYLE BORDER_NONE;
		
		BUTTON IDC_CDCL_CANCEL { NAME CDCL_CANCEL; CENTER_H; SIZE -40,-18; }
		BUTTON IDC_CDCL_REGISTER { NAME CDCL_REGISTER; CENTER_H; SIZE -40,-18; }
		BUTTON IDC_CDCL_PURCHASE { NAME CDCL_PURCHASE; CENTER_H; SIZE -40,-18; }
	}
}
