// C4D-DialogResource

DIALOG DLG_CDSY_ABOUT
{
	NAME CDSY_TITLE;
	GROUP
	{
		COLUMNS 1;
   		BORDERSIZE 8,8,8,8;
		BORDERSTYLE BORDER_GROUP_IN;
		
		USERAREA IDC_CDSY_ABOUT_IMAGE { CENTER_H; SIZE -320,-60; }
		
		STATICTEXT IDC_CDSY_ABOUT_PLUGININFO { NAME CDSY_PLUGININFO; CENTER_H; }
		STATICTEXT IDC_WEBSITE_INFO { NAME WEBINFO; CENTER_H; }
		BUTTON IDC_CDSY_UPDATE { NAME CDSY_UPDATE; CENTER_H; SIZE -240,-18;  }
		
		GROUP
		{
			COLUMNS 1;
			NAME CDSYANSFER_SERIAL;
			BORDERSIZE 12,6,12,6;
			BORDERSTYLE BORDER_GROUP_IN;
			SCALE_H;

			EDITTEXT IDC_CDSY_SERIALNUMBER { SCALE_H; }
		}
	}

	DLGGROUP { OK; }
}
