// C4D-DialogResource

DIALOG DLG_CDSK_REGISTER
{
	NAME CDSK_TITLE;
	GROUP
	{
		COLUMNS 1;
   		BORDERSIZE 8,8,8,8;
		BORDERSTYLE BORDER_GROUP_IN;
		
		USERAREA IDC_CDSK_ABOUT_IMAGE { CENTER_H; SIZE -320,-60; }
		
		STATICTEXT IDC_CDSK_ABOUT_PLUGININFO { NAME CDSK_PLUGININFO; CENTER_H; }
		STATICTEXT IDC_WEBSITE_INFO { NAME WEBINFO; CENTER_H; }
		GROUP
		{
			COLUMNS 1;
			NAME CDSK_SERIAL;
			BORDERSIZE 12,6,12,6;
			BORDERSTYLE BORDER_GROUP_IN;
			SCALE_H;

			EDITTEXT IDC_CDSK_SERIALNUMBER { SCALE_H; }
		}
	}

	GROUP
	{
		COLUMNS 3;
		CENTER_H;
   		BORDERSIZE 8,8,8,8;
		BORDERSTYLE BORDER_NONE;
		
		BUTTON IDC_CDSK_CANCEL { NAME CDSK_CANCEL; CENTER_H; SIZE -40,-18; }
		BUTTON IDC_CDSK_REGISTER { NAME CDSK_REGISTER; CENTER_H; SIZE -40,-18; }
		BUTTON IDC_CDSK_PURCHASE { NAME CDSK_PURCHASE; CENTER_H; SIZE -40,-18; }
	}
}
