CONTAINER tCDSPRConstraint
{
	NAME tCDSPRConstraint;
	DEFAULT 1;
	GROUP
	{
		BUTTON SPRC_PURCHASE {}
	}
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		DEFAULT	1;
		
		GROUP
		{
			COLUMNS 2;
			
			BOOL SPRC_SHOW_LINES {}
			BOOL SPRC_SHOW_GRAVITY {}
		}
		GROUP
		{
			COLUMNS 1;
			
			COLOR SPRC_LINE_COLOR {}
		}
		SEPARATOR {}
		GROUP
		{
			COLUMNS 1;
			
			LINK  SPRC_TARGET { ANIM ON; ACCEPT { Obase; } }
			LINK  SPRC_ATTACHMENT { ANIM ON; ACCEPT { Obase; } }
		}
	}
	GROUP SPRC_ID_SPRING
	{
		DEFAULT	1;
		
		GROUP
		{
			LAYOUTGROUP; COLUMNS 2;
			GROUP
			{
				BOOL SPRC_USE_POSITION {}
				VECTOR SPRC_P_OFFSET { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; }
			}
			GROUP
			{
				BOOL SPRC_USE_ROTATION {}
				VECTOR SPRC_R_OFFSET { UNIT DEGREE;   CUSTOMGUI SUBDESCRIPTION; }
			}
		}
		SEPARATOR { }
		GROUP
		{
			COLUMNS 1;
			
			REAL SPRC_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER;}
		}
		SEPARATOR { LINE; }
		GROUP
		{
			COLUMNS 3;
			
			BOOL SPRC_USE_START_FRAME {}
			BUTTON SPRC_SET_START_FRAME {}
			BUTTON SPRC_RELEASE_START_FRAME {}
		}
	}
	GROUP SPRC_ID_FORCES
	{
		GROUP
		{
			COLUMNS 1;
			
			REAL SPRC_STIFFNESS { UNIT PERCENT; MIN 0.0; MAX 100; }
			REAL SPRC_DAMPING { UNIT PERCENT; MIN 0.0; MAX 200; }
			REAL SPRC_MASS { UNIT REAL; MIN 1.0; MAX 100.0; STEP 0.1; }
			REAL SPRC_OFF_CENTER { UNIT METER; MIN 0.0; STEP 0.1; }
		}
		SEPARATOR { LINE; }
		GROUP SPRC_GRAVITY_GROUP
		{
			COLUMNS 2;
			
			REAL SPRC_GRAVITY { UNIT REAL; STEP 0.1; }
			REAL SPRC_LENGTH { UNIT METER; MIN 0.0; STEP 0.1; }
		}
		GROUP
		{
			COLUMNS 2;
			
			LINK SPRC_GRAV_TARGET { ANIM ON; ACCEPT { Obase; } }
			REAL SPRC_GRAVITY_MIX { UNIT PERCENT; MIN 0.0; MAX 100; }
		}
		SEPARATOR { LINE; }
		GROUP
		{
			COLUMNS 1;
			
			BOOL SPRC_COLLISION {}
		}
		GROUP 
		{
			COLUMNS 3;
			
			REAL SPRC_DEFLECTION { UNIT PERCENT; MIN 0.0; MAX 100; }
			REAL SPRC_BOUNCE { UNIT PERCENT; MIN 0.0; MAX 100; }
			REAL SPRC_FRICTION { UNIT PERCENT; MIN 0.0; MAX 100; }
		}
	}

}