CONTAINER tCDSConstraint
{
	NAME tCDSConstraint;
	DEFAULT 1;
	GROUP
	{
		BUTTON SC_PURCHASE {}
	}
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		DEFAULT	1;
		
		GROUP
		{
			COLUMNS 1;
			
			BOOL SC_SHOW_LINES {}
			COLOR SC_LINE_COLOR {}
		}
		SEPARATOR { LINE; }
		GROUP
		{
			COLUMNS 1;
			
			REAL SC_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER;}
		}
		SEPARATOR {}
		GROUP
		{
			COLUMNS 1;
			
			BOOL SC_USE_AB_MIX {}
			REAL SC_AB_MIX { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER;}
		}
		SEPARATOR {}
		GROUP SC_OFFSETS
		{
			COLUMNS 2;
			
			BOOL SC_AXIS_X { }
			REAL SC_OFFSET_X { UNIT REAL; STEP 0.01; }
			BOOL SC_AXIS_Y { }
			REAL SC_OFFSET_Y { UNIT REAL; STEP 0.01; }
			BOOL SC_AXIS_Z { }
			REAL SC_OFFSET_Z { UNIT REAL; STEP 0.01; }
		}
	}
	GROUP SC_ID_TARGET
	{
		DEFAULT	1;
		GROUP
		{
			COLUMNS 2;
			
			BUTTON SC_ADD_SCA {}
			BUTTON SC_SUB_SCA {}
		}
		SEPARATOR { LINE; }
	}

}