CONTAINER tCDTAConstraint
{
	NAME tCDTAConstraint;
	DEFAULT 1;
	GROUP
	{
		BUTTON TAC_PURCHASE {}
	}
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		DEFAULT	1;
		
		GROUP
		{
			COLUMNS 1;
			
			BOOL TAC_SHOW_LINES {}
			COLOR TAC_LINE_COLOR {}
			SEPARATOR { }
			REAL TAC_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER;}
		}
	}
	GROUP TAC_ID_TARGET
	{
		DEFAULT	1;
		
		GROUP
		{
			COLUMNS 1;
			
			LINK  TAC_TARGET { ANIM ON; ACCEPT { Obase; } }
		}
		SEPARATOR { LINE; }
		GROUP
		{
			COLUMNS 1;
			
			BUTTON TAC_RESET_POSITION {}
		}
	}
	GROUP TAC_ID_STRIDE
	{
		GROUP
		{
			COLUMNS 3;
			
			REAL TAC_SPEED { UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0; }
			REAL TAC_LENGTH { UNIT METER; MIN 0.0; STEP 1.0; }
			REAL TAC_HEIGHT { UNIT METER; MIN 0.0; STEP 1.0; }
		}
		SEPARATOR { }
		GROUP
		{
			COLUMNS 1;
			
			REAL TAC_OVERSTEP { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER;}
		}
		SEPARATOR { }
		GROUP
		{
			COLUMNS 1;
			
			SPLINE TAC_HEIGHT_SPLINE
			{ 
				SHOWGRID_H; 
				SHOWGRID_V; 

				GRIDSIZE_H 8; 
				GRIDSIZE_V 8; 

				HAS_PRESET_BTN; 

				MINSIZE_H 120;
				MINSIZE_V 80; 

				EDIT_H; 
				EDIT_V; 

				LABELS_H; 
				LABELS_V; 

				HAS_ROUND_SLIDER;

				X_MIN 0; 
				X_MAX 1.00; 

				Y_MIN 0; 
				Y_MAX 1.00; 

				X_STEPS 0.1; 
				Y_STEPS 0.1;
			}	
		}
		SEPARATOR { LINE; }
		GROUP
		{
			COLUMNS 3;
			
			BOOL TAC_USE_START_FRAME {}
			BUTTON TAC_SET_START_FRAME {}
			BUTTON TAC_RELEASE_START_FRAME {}
		}
	}
}