CONTAINER tCDMorphSlider
{
	NAME tCDMorphSlider;
	DEFAULT 1;
	GROUP
	{
		BUTTON MS_PURCHASE {}
	}
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{		
		GROUP
		{
			COLUMNS 2;
			
			BOOL MS_SHOW_BOX { } 
			BOOL MS_SHOW_DIAGONAL { } 
		}	
		COLOR MS_BOX_COLOR {}
		VECTOR MS_BOX_POSITION	{ UNIT METER; }
		REAL MS_BOX_SIZE_X { UNIT REAL; MIN 0.0;}
		REAL MS_BOX_SIZE_Y { UNIT REAL; MIN 0.0;}
		SEPARATOR {}
		BUTTON MS_HOME_POSITION {}
	}
	GROUP MS_OUTPUT_VALUES
	{
		GROUP
		{
			COLUMNS 1;
			BOOL MS_MIX_X_Y { } 
		}	
		GROUP
		{
			COLUMNS 3;
			
			REAL MS_OUTPUT_X { UNIT PERCENT; ANIM OFF;}
			BOOL MS_POSITIVE_X { } 
			BOOL MS_NEGATIVE_X { } 
			REAL MS_OUTPUT_Y { UNIT PERCENT; ANIM OFF;}
			BOOL MS_POSITIVE_Y { } 
			BOOL MS_NEGATIVE_Y { } 
		}	
	}
	GROUP MS_MORPH_CONTROL
	{
	}
}	