enum
{
	// string table definitions
	D_WP_RADIUS				= 1000,
	D_WP_VISIBLE_ONLY		= 1001,
	D_WP_STRENGTH			= 1002,
	D_WP_CONTRAST			= 1003,
	
	D_WP_MODE				= 1004,
		D_WP_MODE_SET		= 1005,
		D_WP_MODE_ADD		= 1006,
	
	D_WP_DYN_GROUP			= 1007,
	D_WP_DYN_TITLE			= 1008,
	D_WP_DYN_STRENGTH		= 1009,		
	
	D_WP_JLIST				= 1010,
	D_WP_JLIST_EXPAND		= 1011,
	D_WP_JCOLORS			= 1012,
	D_WP_SOFT_EDGES			= 1013,
	D_WP_SOFTNESS			= 1014,
		D_WP_MODE_BLEND		= 1015,
	D_WP_NORMALIZED			= 1016,
	
	
	IDS_CDCLOTH					= 10000,
	IDS_ABOUT_CDCL,
	
	IDS_CDCLTAG,
	IDS_CDRPTAG,
	IDS_CDCLDRTAG,
	
	IDS_CDADDCL,
	IDS_CDADDRP,
	IDS_CDUNCLOTH,
	

	DLG_CDCL_ABOUT				= 20000,
	DLG_CDCL_REGISTER,
	
	IDC_CDCL_ABOUT_IMAGE,
	IDC_CDCL_ABOUT_PLUGININFO,
	IDC_CDCL_SERIALNUMBER,
	IDC_CDCL_UPDATE,
	
	IDC_CDCL_EULA,
	IDC_CDCL_AGREE,
	IDC_CDCL_DISAGREE,
	
	IDC_CDCL_CANCEL,
	IDC_CDCL_REGISTER,
	IDC_CDCL_PURCHASE,
	
	MD_THANKYOU,
	MD_INVALID_NUMBER,
	IDS_WEB_SITE,
	
	C_SYMBOL,
	
	IDS_CDSKINREF,
	IDS_CDCLUSTERTAG,

	
	_DUMMY_ELEMENT_
};
