// C4D-DialogResource

DIALOG DLG_CDM_REGISTER
{
	NAME CDM_TITLE;
	GROUP
	{
		COLUMNS 1;
   		BORDERSIZE 8,8,8,8;
		BORDERSTYLE BORDER_GROUP_IN;
		
		USERAREA IDC_CDM_ABOUT_IMAGE { CENTER_H; SIZE -320,-60; }
		
		STATICTEXT IDC_CDM_ABOUT_PLUGININFO { NAME CDM_PLUGININFO; CENTER_H; }
		STATICTEXT IDC_WEBSITE_INFO { NAME WEBINFO; CENTER_H; }
		GROUP
		{
			COLUMNS 1;
			NAME CDM_SERIAL;
			BORDERSIZE 12,6,12,6;
			BORDERSTYLE BORDER_GROUP_IN;
			SCALE_H;

			EDITTEXT IDC_CDM_SERIALNUMBER { SCALE_H; }
		}
	}

	GROUP
	{
		COLUMNS 3;
		CENTER_H;
   		BORDERSIZE 8,8,8,8;
		BORDERSTYLE BORDER_NONE;
		
		BUTTON IDC_CDM_CANCEL { NAME CDM_CANCEL; CENTER_H; SIZE -40,-18; }
		BUTTON IDC_CDM_REGISTER { NAME CDM_REGISTER; CENTER_H; SIZE -40,-18; }
		BUTTON IDC_CDM_PURCHASE { NAME CDM_PURCHASE; CENTER_H; SIZE -40,-18; }
	}
}
