// C4D-DialogResource

DIALOG DLG_CDM_ABOUT
{
	NAME CDM_TITLE;
	GROUP
	{
		COLUMNS 1;
   		BORDERSIZE 8,8,8,8;
		BORDERSTYLE BORDER_GROUP_IN;
		
		USERAREA IDC_CDM_ABOUT_IMAGE { CENTER_H; SIZE -320,-60; }
		
		STATICTEXT IDC_CDM_ABOUT_PLUGININFO { NAME CDM_PLUGININFO; CENTER_H; }
		STATICTEXT IDC_WEBSITE_INFO { NAME WEBINFO; CENTER_H; }
		BUTTON IDC_CDM_UPDATE { NAME CDM_UPDATE; CENTER_H; SIZE -240,-18;  }
		
		GROUP
		{
			COLUMNS 1;
			NAME CDMORPH_SERIAL;
			BORDERSIZE 12,6,12,6;
			BORDERSTYLE BORDER_GROUP_IN;
			SCALE_H;

			EDITTEXT IDC_CDM_SERIALNUMBER { SCALE_H; }
		}
	}

	DLGGROUP { OK; }
}
